swagger: "2.0"
info:
  description: API pour la gestion des transactions bancaires de l'application Argent Bank
  version: 1.0.0
  title: Argent Bank Transactions API

host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /transactions:
    get:
      security:
        - Bearer: []
      summary: Liste toutes les transactions pour le mois en cours, groupées par compte
      description: Retourne une liste de toutes les transactions pour l'utilisateur authentifié, divisées par compte.
      responses:
        "200":
          description: Une liste de transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "401":
          description: Non autorisé

  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      summary: Détails d'une transaction spécifique
      description: Retourne les détails d'une transaction spécifique en utilisant son ID.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Détails de la transaction
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Non autorisé
        "404":
          description: Transaction non trouvée

    post:
      security:
        - Bearer: []
      summary: Créer une nouvelle transaction
      description: Crée une nouvelle transaction pour l'utilisateur authentifié.
      parameters:
        - in: body
          name: transaction
          description: Les attributs de la transaction à créer
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "201":
          description: Transaction créée
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Non autorisé
        "404":
          description: Compte non trouvé

    put:
      security:
        - Bearer: []
      summary: Modifier une transaction existante
      description: Permet de modifier les détails d'une transaction existante.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: transaction
          description: Les attributs de la transaction à mettre à jour
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Transaction mise à jour
        "401":
          description: Non autorisé
        "404":
          description: Transaction non trouvée

    delete:
      security:
        - Bearer: []
      summary: Supprimer une transaction
      description: Supprime une transaction spécifique de l'utilisateur.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Transaction supprimée
        "401":
          description: Non autorisé
        "404":
          description: Transaction non trouvée
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
