swagger: "2.0"
info:
  description: API pour la gestion des transactions bancaires de l'application Argent Bank
  version: 1.0.0
  title: Argent Bank Transactions API

host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /{accountId}/transactions:
    get:
      security:
        - Bearer: []
      summary: Liste toutes les transactions pour un compte spécifié
      description: Retourne une liste de toutes les transactions pour un compte donné.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Une liste de transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "401":
          description: Non autorisé

  /{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      summary: Détails d'une transaction spécifique
      description: Retourne les détails d'une transaction spécifique en utilisant son ID.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Détails de la transaction
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Non autorisé
        "404":
          description: Transaction non trouvée

    patch:
      security:
        - Bearer: []
      summary: Modifier une transaction existante
      description: Permet de modifier les détails d'une transaction existante.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: transaction
          description: Les attributs de la transaction à mettre à jour
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Transaction mise à jour
        "401":
          description: Non autorisé
        "404":
          description: Transaction non trouvée

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        readOnly: true
      date:
        type: string
        format: date
        readOnly: true
      amount:
        type: number
        readOnly: true
      balance:
        type: number
        readOnly: true
      category:
        type: string
        description: La catégorie de la transaction
      note:
        type: string
        description: Une note personnelle ajoutée à la transaction
